# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipos_tareas',
            options={'verbose_name_plural': 'Tipos_tareas'},
        ),
    ]
