# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20160413_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonas',
            name='provincia',
            field=models.CharField(default='Pontevedra', max_length=75),
        ),
    ]
