# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20160427_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
